version: "3.7"
services:

  # todo-database
  todo-database:
    image: postgres:latest
    container_name: todo-database
    ports:
      - 5432:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    restart: always